### ISSUE TITLE
Filter out MMDA prohibited roads to create: Metro Manila graph without prohibited roads, and Metro Manila prohibited roads

### ISSUE THREAD

**Issue by Pipluppp** [Pipluppp/ebike-ncr#1]
Current Metro Manila graph of nodes and edges [`metro_drive.graphml`](https://github.com/Pipluppp/ebike-ncr/blob/8cb0f0618f976328de9e54ae3f9ed3c1892264e9/data/metro_drive.graphml) contains all the driveable roads in Metro Manila. 

But we need to remove all the following prohibited roads/edges since we only want to run our Dijkstra algorithm on valid edges

1. **C1:** Recto Avenue
2. **C2:** Pres. Quirino Avenue
3. **C3:** Araneta Avenue
4. **C4:** EDSA
5. **C5:** Katipunan/CP Garcia
6. **C6:** Southeast Metro Manila Expressway
7. **R1:** Roxas Boulevard
8. **R2:** Taft Avenue
9. **R3:** Osmeña Highway
10. **R4:** Shaw Boulevard
11. **R5:** Ortigas Avenue
12. **R6:** Magsaysay Blvd./Aurora Blvd.
13. **R7:** Quezon Ave./Commonwealth Ave.
14. **R8:** A. Bonifacio Ave.
15. **R9:** Rizal Ave.
16. **R10:** Del Pan/Marcos Highway/McArthur Highway
17. Elliptical Road
18. Mindanao Avenue
19. Marcos Highway
20. Boni Avenue (Mandaluyong)
21. España Blvd.

Work on https://github.com/Pipluppp/ebike-ncr/blob/8cb0f0618f976328de9e54ae3f9ed3c1892264e9/remove_prohibited_roads.ipynb

1. Create initial `prohibited_roads` by taking all the roads in our current Metro Manila graph edges which has the `highway` type of motorway/trunk/primary
2. Then add/remove roads as needed until it matches all the prohibited roads for e-bikes

Final output should be a `metro_graph_without_prohibited.graphml` of the Metro Manila graph with no prohibited roads/edges

**Comment by Lannzo** [comment]
bump
