### ISSUE TITLE
Right-click context menu to choose starting and ending points

### ISSUE THREAD

**Issue by Pipluppp** [Pipluppp/ebike-ncr#2]
Currently, the source is fixed and we use left-click for selecting different destinations. We'll try to copy the functionality of Google Maps

**Requirements**

- Right-Click for Starting and Ending Points: Allow users to right-click to choose the starting point and end point.
- Dynamic Update on Subsequent Right-Clicks: The map should be capable of updating the start and end points on subsequent right-clicks, assuming a route has already been chosen.

**Example**
Suppose the source is point A and the target is point B, and a route has been drawn.

If the user right-clicks on a different location to change the source (or the target) to point C, the map should update to display the new route from source C to target B.

Example JSFiddle from Claude 3.5 that mimics the Google Maps right-click context menu with dark mode: [JSFiddle Link](https://jsfiddle.net/3skm78fo/)

**Comment by ghost** [comment]
gew
